// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAInjOR1PBpru63DKOws6YG1EjOFlUv864',
    appId: '1:546586877362:web:c0f0895e091ebcfd60d8ab',
    messagingSenderId: '546586877362',
    projectId: 'mtn-module-5-e370f',
    authDomain: 'mtn-module-5-e370f.firebaseapp.com',
    storageBucket: 'mtn-module-5-e370f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhL35DjPlItMTwGhicsDlfuTH-BZRCmKI',
    appId: '1:546586877362:android:790c5fdb0ae0232660d8ab',
    messagingSenderId: '546586877362',
    projectId: 'mtn-module-5-e370f',
    storageBucket: 'mtn-module-5-e370f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPedlk5zMFWMZX9m7HK0mNqiHZe3T62NI',
    appId: '1:546586877362:ios:373a706b3d18bdd060d8ab',
    messagingSenderId: '546586877362',
    projectId: 'mtn-module-5-e370f',
    storageBucket: 'mtn-module-5-e370f.appspot.com',
    iosClientId: '546586877362-fq4j29rqt151q7c1hf5dkj3srqklktp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mtnAppAcademyModule3',
  );
}
